// <auto-generated />
namespace Jobboard.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Jobboardprj : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Jobboardprj));
        
        string IMigrationMetadata.Id
        {
            get { return "202101161508218_Jobboardprj"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
